# .golangci.yml
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - revive
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - dupImport
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G104
      - G107
      - G304

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0